name: AWS OIDC Test

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  test-aws-oidc:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::714258651552:role/github-role
          role-session-name: GitHubActionsSession
          aws-region: us-east-1

      - name: List S3 Buckets
        run: aws s3 ls